language: php

before_script:
  - composer global require hirak/prestissimo
  - composer install
  - docker pull lkdevelopment/hetzner-cloud-api-mock
  - docker run -d -p 127.0.0.1:4000:8080 lkdevelopment/hetzner-cloud-api-mock
  - docker ps -a
  # list any PHP version you want to test against
php:
  # aliased to a recent 7.x version
  - 7.1
  - 7.2
  - 7.3

services:
  - docker

script: vendor/bin/paratest -p8 tests
